name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Exécution sur un runner Ubuntu

    steps:
      # Étape 1: Checkout du code
      - uses: actions/checkout@v4  # Utilisation de la version 4 de checkout action

      # Étape 2: Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5  # Utilisation de la version 5 de setup-python
        with:
          python-version: '3.x'  # Vous pouvez spécifier la version exacte comme '3.11' si nécessaire

      # Étape 3: Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Mise à jour de pip
          pip install -r requirements.txt  # Installation des dépendances depuis requirements.txt

      # Étape 4: Installation de pytest et pytest-cov pour la couverture de tests
      - name: Install pytest and pytest-cov
        run: |
          pip install pytest pytest-cov  # Installation de pytest et du plugin de couverture

      # Étape 5: Lancer les tests avec pytest
      - name: Test with pytest
        run: |
          pytest bi_project/test_environment.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          # Ici, vous pouvez spécifier le fichier de test exact ou un répertoire de tests complet
